# Generated by Django 3.1.1 on 2021-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaudioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('audio_type', models.CharField(choices=[('Song', 'Song'), ('Podcast', 'Podcast'), ('Audiobook', 'Audiobook')], max_length=10)),
                ('author_of_the_title', models.CharField(blank=True, max_length=100, null=True)),
                ('narrator', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', models.CharField(blank=True, max_length=1000, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
